version: "2"

services:

  web:
    build:
      context: "services/web"
    environment:
      REDIRECT: "https://registry.jsonresume.org/mgomezch"

  haproxy:
    image: "bradjonesllc/docker-haproxy-letsencrypt"
    restart: "always"
    links:
      - "web:www"
    environment:
      CERTS: "mgomez.ch"
      EMAIL: "targen@gmail.com"
      SERVICE_80_NAME: "website-http"
      SERVICE_80_CHECK_TCP: "true"
      SERVICE_80_CHECK_INTERVAL: "30s"
      SERVICE_80_CHECK_TIMEOUT: "15s"
      SERVICE_80_TAGS: "prefixhttp-mgomez.ch/"
      SERVICE_443_NAME: "website-https"
      SERVICE_443_CHECK_TCP: "true"
      SERVICE_443_CHECK_INTERVAL: "30s"
      SERVICE_443_CHECK_TIMEOUT: "15s"
      SERVICE_443_TAGS: "prefixhttps-mgomez.ch/"
    labels:
      SERVICE_NAME: "website-proxy"
    volumes:
      - "./data/letsencrypt:/etc/letsencrypt"

networks:
  default:
    external:
      name: "localservices_default"
