version: "2"

services:

  web:
    build:
      context: "services/web"
    environment:
      REDIRECT: "https://registry.jsonresume.org/mgomezch"

  haproxy:
    image: "bradjonesllc/docker-haproxy-letsencrypt"
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    links:
      - "web:www"
    environment:
      CERTS: "mgomez.ch"
      EMAIL: "targen@gmail.com"
    volumes:
      - "./data/letsencrypt:/etc/letsencrypt"
